[package]
name = "repeat_in_rust"
version = "0.1.0"
authors = ["SimonMTS <info@simonstriekwold.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.1.3"